# ~/.zprofile
# Zsh login shell configuration for environment and PATH setup
# Managed by: ~/.dotfiles/zsh/zprofile
# Author: Simge Ekiz
# License: MIT

export ZPROFILE_LOADED=1

[ -r $HOME/.dotfiles/zsh/env.zsh ] && source $HOME/.dotfiles/zsh/env.zsh
[ -r $HOME/.dotfiles/zsh/path.zsh ] && source $HOME/.dotfiles/zsh/path.zsh