# ~/.zprofile
# Zsh login shell configuration for environment and PATH setup
# Managed by: ~/.dotfiles/zsh/zprofile
# Author: Simge Ekiz
# License: MIT

[ -r $HOME/.dotfiles/zsh/env.zsh ] && source $HOME/.dotfiles/zsh/env.zsh

