# ~/.zshenv
# Zsh environment variables
# Managed by: ~/.zshenv
# Author: Simge Ekiz
# License: MIT

# environment variables
export LANG="en_US.UTF-8"
export EDITOR="nano"
export PAGER="less"
export VIRTUAL_ENV_DISABLE_PROMPT=1