# ~/.zshenv
# Zsh environment variables
# Managed by: ~/.zshenv
# Author: Simge Ekiz
# License: MIT

# === Environment variables ===
export LANG="en_US.UTF-8"
export EDITOR="nano"
export PAGER="less"
export VIRTUAL_ENV_DISABLE_PROMPT=1

# === NVM (Node Version Manager) ===
export NVM_DIR="$HOME/.nvm"
