# ~/.bash_logout
# Executed when a login bash shell exits.
# Managed via: ~/.dotfiles/bash/bash_logout
# Author: Simge Ekiz
# License: MIT

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
